// Generated by Wrangler on Tue Dec 31 2024 16:11:31 GMT+0100 (Midden-Europese standaardtijd)
// by running `wrangler types`

interface Env {
	SPOTIFY_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
}
